### ISSUE TITLE
Problem acessing the /data/populate route

### ISSUE THREAD

**Issue by SiriusFuenmayor** [steniowagner/bon-appetit-server#3]
Hi Stenio, I have follow the instructions and successfully installed the app and the server. I can access all the routes except the /data/populate route. When I enter

http://localhost:3001/bon-appetit/api/v1/data/populate

in my browser I get the error:

`Error: Not Found
    at /home/sfuenmayor/Development/bon-appetit-server/src/app.js:12:15
    at Layer.handle [as handle_request] (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:317:13)
    at /home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:275:10)
    at /home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:260:14)
    at /home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:635:15
    at next (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:317:13)
    at /home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/sfuenmayor/Development/bon-appetit-server/node_modules/express/lib/router/index.js:335:12)`

**Comment by SiriusFuenmayor** [comment]
Sorry for my lack of knowledge in the subject but I guess that you can't make POST requests by entering the route in a web browser anyway I solved my issue and filled the database by running the following command in a terminal:

`curl -X POST http://localhost:3001/bon-appetit/api/v1/data/populate`
